name: "Forge Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Run Forge tests
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge install
        run: |
          cd contracts
          forge --version
          forge install
        id: install

      - name: Run Forge build
        run: |
          cd contracts
          forge --version
          forge clean
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd contracts
          forge test -vvv
        id: test
